### ISSUE TITLE
Not very graceful exit from CTRL-C

### ISSUE THREAD

**Issue by m3dwards** [bitcoin-dev-project/sim-ln#94] opened 2023-09-11 14:23 UTC
I used `CTRL-C` to stop sim-ln and got a bunch of panics:

```
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4566 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4571 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4576 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4581 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4586 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4591 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4596 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4601 panicked
2023-09-11T14:01:59.526Z ERROR [sim_lib] Simulation results producer task exited with error: task 4606 panicked
```

**Comment by carlaKC** [comment] 2023-09-11 14:40
Hm, I suspect that this may be because we need to merge #75 and you were running with CLN activity - will check it out!

**Comment by sr-gi** [comment] 2023-09-13 20:35
Can we confirm this @maxwedwards?

**Comment by maxwedwards** [comment] 2023-09-13 20:36
I can confirm I was running CLN as well as LND. If you need I can try it without a CLN node.

**Comment by sr-gi** [comment] 2023-09-13 20:38
Oh no, I mean if you can try it out now that #75 is merged

**Comment by maxwedwards** [comment] 2023-09-15 12:04
I'm struggling to get it to run now. I keep getting:`

```shell
2023-09-15T11:59:44.191Z INFO [sim_cli] Connected to 03842469335b6ebaa457 - Node ID: 03842469335b6ebaa45726c8d7b15e6df00f7802b347abc34216535881d6a82ef4.
2023-09-15T11:59:44.197Z INFO [sim_cli] Connected to BIZARREFEED-v23.08-modded - Node ID: 026ba0f8fd6d39f5dfd59cbfcb58dbe828512d97ee3a2f5c17736497e28c3b8a34.
2023-09-15T11:59:44.198Z INFO [sim_lib] Running the simulation forever.
Error: Lightning Error: GetNodeInfoError("Get node info error status: NotFound, message: \"unable to find node\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\"} }")

Caused by:
    Get node info error Get node info error status: NotFound, message: "unable to find node", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```

I've stared at the config file and limited it to just one activity and checked and rechecked the pubkeys and they seem correct to me. What am I missing? My config:

```json
{
  "nodes": [
    {
      "LND": {
        "id": "03842469335b6ebaa45726c8d7b15e6df00f7802b347abc34216535881d6a82ef4",
        "address": "https://localhost:28103",
        "macaroon": "/Users/max/source/sim-ln/auth/carol/admin.macaroon",
        "cert": "/Users/max/source/sim-ln/auth/carol/tls.cert"
      }
    },
    {
      "CLN": {
        "id": "026ba0f8fd6d39f5dfd59cbfcb58dbe828512d97ee3a2f5c17736497e28c3b8a34",
        "address": "https://localhost:28101",
        "ca_cert": "/Users/max/source/sim-ln/auth/alice/ca.pem",
        "client_cert": "/Users/max/source/sim-ln/auth/alice/client.pem",
        "client_key": "/Users/max/source/sim-ln/auth/alice/client-key.pem"
      }
    }
  ],
  "activity": [
    {
      "destination": "026ba0f8fd6d39f5dfd59cbfcb58dbe828512d97ee3a2f5c17736497e28c3b8a34",
      "source": "03842469335b6ebaa45726c8d7b15e6df00f7802b347abc34216535881d6a82ef4",
      "interval_secs": 1,
      "amount_msat": 2000
    }
  ]
}
```

**Comment by carlaKC** [comment] 2023-09-15 14:59
I suspect that this has something to do with gossip sync - when running on the regular settings there's a lot of time and block based rate limiting that goes on that's suuuper annoying for local dev. Building CLN in dev mode with `--dev-fast-gossip ` helps a lot, but (afaik) LND doesn't have a similar setting. 

Should be able to confirm that issue with: `cl listnodes | grep {pubkey}`?

On the sim-ln side, I think that we should expand our wait logic to more gracefully handle this by adding some backoffs / retry loop. Where we won't be able to address this is if it's a block height based local sync problem, but we can at least prompt that.

**Closed** 2024-03-06 12:10 UTC
